### ISSUE TITLE
Doesn't work on 10.11

### ISSUE THREAD

**Issue by adam1x** [anthonygelibert/QLColorCode#10]
I tried putting it in ~/Library/QuickLook and /Library/QuickLook, but neither seems to work. (After qlmanage -r) QuickLook would load for a while, and then revert back to the default view.

**Comment by anthonygelibert** [comment]
It’s pretty strange… I personally use it on 10.11.6… 
Have you installed highlight ?

**Comment by adam1x** [comment]
Oh you need highlight for this to work? I'll try installing that later! Thanks!

**Comment by adam1x** [comment]
I installed highlight (brew install highlight) and it worked! Thanks a lot!
