### ISSUE TITLE
QLColorCode Does Not Load

### ISSUE THREAD

**Issue by DannyNemer** [anthonygelibert/QLColorCode#11]
With `QLColorCode` installed, Quick Look fails to generate Quick Look previews for any source files. Uninstalling and reinstalling (via commands listed below) does not work, neither does rebooting. (Other plugins continue to work; e.g., `QLMarkdown`, `QuickLookJSON`.)

Thank you for your help!

**System**: OS X 10.11.6
**Installation**:
```shell
brew install highlight
brew cask install qlcolorcode
```

<img width="857" alt="screen shot 2016-09-19 at 1 09 45 pm" src="https://cloud.githubusercontent.com/assets/170023/18641388/658a286c-7e6a-11e6-88b7-0ff66792d621.png">

**Comment by anthonygelibert** [comment]
Hi Danny,

Can you please open a terminal and execute this command on the server.js file (copy-paste the result here) :

``qlmanage -p -d2 server.js``

This command will preview the given file with QL with the debug level 2.

Regards,
Anthony.

**Comment by DannyNemer** [comment]
Solved: I had `QLColorCode` configured with a theme absent from the latest version of `highlight`: `ide-xcode.theme`. I chose a different theme via `defaults write org.n8gray.QLColorCode hlTheme`, and `QLColorCode` works flawlessly.

Thank you!
