### ISSUE TITLE
Handling .yml etc.

### ISSUE THREAD

**Issue by nkalvi** [anthonygelibert/QLColorCode#16]
In https://github.com/anthonygelibert/QLColorCode/blob/master/Info.plist#L23 
I'm wondering whether
```xml
<string>public.tex</string>
```
should be
```xml
<string>public.text</string>
```
Then QuickLook will work on *.yml* etc.

**Comment by anthonygelibert** [comment]
I always thought public.tex was for LaTeX, but, maybe, I was wrong… I will look at this change.

**Comment by anthonygelibert** [comment]
It's in the commit 29065fa0ac9fd2be401b1eafe4cb2ba8ed3b9e75.

**Comment by nkalvi** [comment]
May be, I'm not sure (I saw `<string>org.tug.tex</string>` in the same section).

Adding the type as an extra entry may work (current version of TextMate 2 has that entry) -
it worked well with *.yml* in my testing.

**Comment by anthonygelibert** [comment]
I added it… I think that can't harm and can solve several new kind of documents… I think the tradeoff is pretty good.

**Comment by nkalvi** [comment]
Thanks!

**Comment by anthonygelibert** [comment]
Thanks to you!
