### ISSUE TITLE
failed with QLColorCode: colorize.sh failed with exit code 101. 

### ISSUE THREAD

**Issue by hadesh** [anthonygelibert/QLColorCode#17]
the error log is:
QuickLookSatellite[1902]: QLColorCode: colorize.sh failed with exit code 101.  Command was ('/Users/xxx/Library/QuickLook/QLColorCode.qlgenerator/Contents/Resources/colorize.sh' '/Users/xxx/Library/QuickLook/QLColorCode.qlgenerator/Contents/Resources' '/Users/xxx/Desktop/github/xxx/DisplayViewController.swift' 0).

my mpb: 10.11.6

**Comment by ildar-gilfanov** [comment]
I have the same issue.

**Comment by anthonygelibert** [comment]
Sorry guys.

Can you please open a terminal and execute this command on the DisplayViewController.swift file (copy-paste the result here) :

qlmanage -p -d2 DisplayViewController.swift

This command will preview the given file with QL with the debug level 2.

Regards,
Anthony.

**Comment by ildar-gilfanov** [comment]
Sure

**Comment by anthonygelibert** [comment]
**go4it:9: no such file or directory: /opt/local/bin/highlight
go4it:9: no such file or directory: /opt/local/bin/highlight**

Indicates that highlight isn't installed on your system.

**Comment by anthonygelibert** [comment]
It's in the manual:

> Warning: my fork uses an external Highlight. It will attempt to find highlight on your PATH (so it should work out of the box for homebrew and MacPorts), but if it can't find it, it'll use /opt/local/bin/highlight (MacPorts default). This can be changed:
> 
> defaults write org.n8gray.QLColorCode pathHL /path/to/your/highlight

**Comment by ildar-gilfanov** [comment]
@anthonygelibert Previous version of QLColorCode worked good on my system. Is it a new dependency?

**Comment by ildar-gilfanov** [comment]
Oh. Looks like I used another fork. Thank you very much!

**Comment by anthonygelibert** [comment]
No problem 👍.

**Comment by ildar-gilfanov** [comment]
It works now. Thank you!

**Comment by anthonygelibert** [comment]
@hadesh Can you run the command, please?

**Comment by hadesh** [comment]
I think it is the same issue with 'highlight'.  Thanks anyway.
