### ISSUE TITLE
Update download location

### ISSUE THREAD

**Issue by tsparber** [anthonygelibert/QLColorCode#2]
GitHub has a nice [releases](https://github.com/blog/1547-release-your-software) feature. Would you mind to move the binary there?

Updating the [tag/release-2.0.4](https://github.com/anthonygelibert/QLColorCode/releases/tag/release-2.0.4) should be enough :smiley:

**Comment by anthonygelibert** [comment]
I’ve tried to do it. I compiled a clean version and edited the [tag/release-2.0.4](https://github.com/anthonygelibert/QLColorCode/releases/tag/release-2.0.4).

I close the issue but don’t hesitate to reopen it if I made a mistake.

Thanks for the advice 😊.

**Comment by tsparber** [comment]
Thank you! I updated the cask to reflect the changes and included the `highlight` dependency.
(https://github.com/caskroom/homebrew-cask/pull/17361)
