### ISSUE TITLE
Auto detect encoding？

### ISSUE THREAD

**Issue by goodman-capu** [anthonygelibert/QLColorCode#20]
Can this plugin auto detect text encoding rather than using an UTF-8 default?
The original system's plugin for txt format can auto detect non-UTF-8 encoding like GB2312 and GBK, but this plugin overrides that, thus many Chinese files on my computer becomes unreadable using this plugin.

**Comment by goodman-capu** [comment]
Besides, the auto-wrap function turns some UTF-8 characters into non-UTF-8 characters. Maybe it's the problem with the length of a character, for English it's 2, but for Chinese or Emoji, it can be 3 or 4
<img width="506" alt="2016-12-29 12 04 29" src="https://cloud.githubusercontent.com/assets/8862302/21525822/af9eaefc-cd5a-11e6-8f41-52e68b748140.png">

**Comment by anthonygelibert** [comment]
Thanks for the report (and sorry for this answer delay). 

I will investigate it!

**Comment by anthonygelibert** [comment]
Besides autodetection there are "textEncoding" and "webkitTextEncoding" settings. I look at auto detection.

**Comment by anthonygelibert** [comment]
I had never the time (and, I will be honest, the interest) into properly investigating this issue. If someone is interested, he can investigates and reopen later this issue…
