### ISSUE TITLE
Correct an improper (empty) pathHL

### ISSUE THREAD

**Issue by anthonygelibert** [anthonygelibert/QLColorCode#22]
See #20.

**Comment by dnicolson** [comment]
An incorrect `pathHL` (non-empty) value would also need to be corrected. Following the steps https://github.com/anthonygelibert/QLColorCode/issues/6#issuecomment-210997449 failed to update the `pathHL` value.

`which highlight` returns "/usr/local/bin/highlight" but the value of `pathHL` is "/usr/local/opt/highlight/bin", it does work if hardcoded to "/usr/local/opt/highlight/bin/highlight" though.
