### ISSUE TITLE
Adding Typescript

### ISSUE THREAD

**Issue by afhrad** [anthonygelibert/QLColorCode#23]
Any chance to include Typescript to the preview? I struggled a bit adding it to the info.plist file. As the extension ".ts" defaults to the UTI `public.mpeg-2-transport-stream` the movie preview will always show up. Here is the tree for the registered UTIs:

    kMDItemContentTypeTree = (
        "public.item",
        "public.movie",
        "public.audiovisual-content",
        "public.mpeg-2-transport-stream",
        "public.data",
        "public.content"
    )

Anyway the best fork of QLColorCode so far !

**Comment by falsanu** [comment]
Well you can move the /System/Library/QuickLook/Movie.qlgenerator file. Then you can see the typescript within the quicklook window...

What I've added then within the Info.plist is:
```xml
<dict>
	<key>UTTypeConformsTo</key>
	<array>
		<string>public.source-code</string>
	</array>
	<key>UTTypeDescription</key>
	<string>Typescript files</string>
	<key>UTTypeIdentifier</key>
	<string>org.ts.files</string>
	<key>UTTypeTagSpecification</key>
	<dict>
		<key>public.filename-extension</key>
		<array>
			<string>ts</string>
		</array>
	</dict>
</dict>
```
But it does not highlight the .ts files...

**Comment by afhrad** [comment]
Sierra will not allow me to delete anything from the /System/Library/QuickLook folder :(

forcing the QL manager via

    qlmanage -d 4 -g ~/Library/QuickLook/QLColorCode.qlgenerator -c public.source-code -p main.browser.ts

to load the plugin works fine though.

So still investigating

**Comment by falsanu** [comment]
`sudo mv /System/Library/QuickLook/Movie.qlgenerator /tmp`
worked for me to move the file

When I run your command I'll get the correct tumbnail, but not the preview...

**Comment by anthonygelibert** [comment]
@afhrad: Is @falsanu solution OK for you?

**Comment by afhrad** [comment]
Sorry for the late reply. No it is not as I am not able to delete anything from the /System/Library/QuickLook folder (not even with sudo). So any overwrite mechanism would be fine.
Deleting a preinstalled Movie QuickLook plugin is also not a desired solution.

**Comment by bryce-larson** [comment]
Please add `.ts` support out of the box.

**Comment by Albert-Gao** [comment]
Following the instructions in the Readme.md to add `ts` and `tsx`

`.tsx` works with highlighting, but `.ts` is not working. Just showing a big icon: 
![image](https://user-images.githubusercontent.com/18282328/69509949-cb1b4480-0f9f-11ea-8110-b23df372b7a7.png)

**Comment by jpike88** [comment]
is this repo abandoned?

**Comment by anthonygelibert** [comment]
I don't see a way to deal with TS file (*.ts filenames)… QuickLook see them as video files…

**Comment by XuCcc** [comment]
anyone solve it?
