### ISSUE TITLE
Support macOS 10.13

### ISSUE THREAD

**Issue by ilyahal** [anthonygelibert/QLColorCode#26]
Please, add support macOS 10.13

Error message:
> Error: You are using macOS 10.13.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.

**Comment by Nil-Zil** [comment]
The same request, please add 10.13 support.

**Comment by anthonygelibert** [comment]
Sorry men, I haven’t any 10.13 currently 😞… So, you will have to add the support by yourself (or wait for the official release).

**Comment by anthonygelibert** [comment]
I let the ticket open until I support 10.13

**Comment by Nil-Zil** [comment]
Please consider supporting 10.13 since it has been released. Thank you!

**Comment by Suavatore** [comment]
High Sierra support pls

**Comment by anthonygelibert** [comment]
I'm really **really** sorry for the delay taken to support 10.13… I had lots of troubles with my MBP and consequently, I could not release the version… 
Normally, it's now OK and it works in 10.13 (see  2d9ed28).

**Comment by Nil-Zil** [comment]
Thank you for your reply! I still have a little problem with the preview... I expect it should exhibit a complete preview of my code, but currently it shows only a little part of it. Like
[qlc](https://i.imgur.com/AU7avBU.png)
Could you fix it? Thank you!
