### ISSUE TITLE
Plugin breaks quick look functionality with .txt files

### ISSUE THREAD

**Issue by blukas** [anthonygelibert/QLColorCode#27]
While this plugin is located in ~/Library/QuickLook, attempting to preview .txt files shows the filetype icon instead of the content of the .txt file. Currently running macOS 10.12.5, QLColorCode 2.0.8

**Comment by anthonygelibert** [comment]
I know there are differences between a location in /Library/QuickLook and ~/Library/QuickLook. 

It’s on my TODO list to investigate (and list) the differences but I currently lack of time… Sorry.

**Comment by exophunk** [comment]
Is there any update on this?

**Comment by anthonygelibert** [comment]
@exophunk No… sorry… However, I don't forget it… I just lack of time…

**Comment by cogitoxin** [comment]
It took me very long time to find out what's wrong...
Any updates?

**Comment by avishapiro** [comment]
I posted a solution at #32 .
