### ISSUE TITLE
Viewing CSS file always capitalize the property

### ISSUE THREAD

**Issue by qinyuhang** [anthonygelibert/QLColorCode#30]
while quicklook a css file. The image background file name is capitalized. But the real code is not.
`color` -> `Color`
`background` -> `Background`
`logo.png` -> `Logo.png`

<img width="391" alt="2017-11-22 08 39 37" src="https://user-images.githubusercontent.com/6239057/33104016-da59db4a-cf60-11e7-95f6-fec313eb8a73.png">
<img width="341" alt="2017-11-22 08 40 38" src="https://user-images.githubusercontent.com/6239057/33104017-da8d3aa8-cf60-11e7-8c5b-3fcef0c67b28.png">

**Comment by domstubbs** [comment]
I’ve noticed (presumably) the same issue with PHP files with qlcolorcode 2.1.0 installed through brew cask:
<img width="918" alt="screenshot 2018-12-13 at 12 09 13" src="https://user-images.githubusercontent.com/717265/49937916-2dcf1980-fed0-11e8-9897-4522b63b2dd7.png">

<img width="799" alt="screenshot 2018-12-13 at 12 11 04" src="https://user-images.githubusercontent.com/717265/49937927-358ebe00-fed0-11e8-9c0c-dc228d6588ae.png">

**Comment by mmerickel** [comment]
This is also an issue for yaml.

**Comment by darkbrow** [comment]
This behavior caused by default extraHLFlags is set to '-t 4 --kw-case=capitalize ' in the source.
--kw-case=capitalize option makes keywords capitalized in case insensitive languages.
 
To change this behavior, open terminal and enter command below.
```
defaults write org.n8gray.QLColorCode extraHLFlags '-t 4'
```

**Comment by domstubbs** [comment]
Thanks – that’s sorted it.

**Comment by johnelliott** [comment]
Thank you @darkbrow
