### ISSUE TITLE
Not working (for me) on 12.12.6

### ISSUE THREAD

**Issue by jhhobbs** [anthonygelibert/QLColorCode#32]
I can't get the plugin to work.  If it's in either /Library/Quicklook/ or ~/Library/Quicklook/, Quicklook only shows icons, even for filetypes with built in support, like xml, plist, js, txt, etc.  Looked around the internets, couldn't find any hints at to what's up.  Tried downloading multiple compiled versions and building from source.  Anything funky you know of that people have run into?  Also restarted my machine, reset Quicklook and emptied the Quicklook cache half a dozen time.  Any insight would be much appreciated.  Thanks!

**Comment by anthonygelibert** [comment]
Sorry guy.

Can you please open a terminal and execute this command on a file (copy-paste the result here) :

qlmanage -p -d2 <file>

This command will preview the given file with QL with the debug level 2.

Regards,
Anthony.

**Comment by avishapiro** [comment]
I've had the same problem, using Homebrew to install the plugin. When I remove QLColorCode I see a Quicklook preview again. The error message I get on a *.py file is "QLColorCode: colorize.sh failed with exit code 101". The problem may be autodetecting the Highlight tool installed with Homebrew because I also see "go4it:9: no such file or directory: /usr/local/Cellar/highlight/3.41_1/bin". The correct directory should just be  /usr/local/Cellar/highlight/3.41/bin.

**Comment by avishapiro** [comment]
I just found a solution! This has bothered me for weeks.

At the command line type `which highlight`. Put the resulting path into the command `defaults write org.n8gray.QLColorCode pathHL /path/to/your/highlight`.

I believe this will also solve the problem in #27 .

**Comment by jhhobbs** [comment]
@avishapiro - That worked!  Thanks a ton!

**Comment by anthonygelibert** [comment]
So, it's a problem with Cellar not the QLColorCode plugin…
They forgot to update the pathHL value during the highlight update…

**Comment by clayreimann** [comment]
I opened an issue with homebrew https://github.com/caskroom/homebrew-cask/issues/41958

**Comment by Cool-and-Deadly** [comment]
> I just found a solution! This has bothered me for weeks.
> 
> At the command line type `which highlight`. Put the resulting path into the command `defaults write org.n8gray.QLColorCode pathHL /path/to/your/highlight`.
> 
> I believe this will also solve the problem in #27 .

Tried the solution @avishapiro suggested, but highlight is not installed on my Mac. The command returns `highlight not found`. Any other suggestions?
