### ISSUE TITLE
Wrong pathHL setting after using brew cask to upgrade to version 2.0.9

### ISSUE THREAD

**Issue by AnyOfYou** [anthonygelibert/QLColorCode#33]
After use brew cask to upgrade qlcolorcode to 2.0.9, the pathHL is set to "/usr/local/Cellar/highlight/3.40_1/bin", but the path isn't really exists on my disk (Under the path /usr/local/Cellar/highlight/, it has a folder named 3.39, but no 3.40_1 exists in there). Because that, the plugin can not be able to work properly.
So I checked my another computer, which been installed qlcolorcode version 2.0.8. The pathHL is set to "/usr/local/bin/highlight". I also do diff on version 2.0.8 and 2.0.9 brew install script (Via `brew cask cat qlcolorcode`), found the difference here.

on 2.0.8:

> postflight do
    # This sets the path to the highlight binary to the preferred one found in $PATH.
    system 'defaults write org.n8gray.QLColorCode pathHL "$(which highlight)"'
end

on 2.0.9:

>   postflight do
    system_command '/usr/bin/defaults', args: ['write', 'org.n8gray.QLColorCode', 'pathHL', "#{HOMEBREW_PREFIX}/bin/highlight"]
  end

So I manually set the pathHL to "/usr/local/bin/highlight", which is a symbolic link of "/usr/local/Cellar/highlight/3.39/bin/highlight", everything is working now.

**Comment by mfullbrook** [comment]
It's been fixed in https://github.com/caskroom/homebrew-cask/blob/master/Casks/qlcolorcode.rb 

Do this to fix
```
brew update
brew cask install qlcolorcode
```
