### ISSUE TITLE
C# preview not working

### ISSUE THREAD

**Issue by programming-wolf** [anthonygelibert/QLColorCode#34]
Hi, 

I am trying to preview C# files (*.cs), but it does only show me the default macOS preview of a file icon and its name. If I install the qlstephen plugin, I can at least see the content (without highlighting, of course). 

Do you have any idea what the problem could be? Javascript files are not highlighted, either. 😢 

macOS 10.13.2, installed via brew cask.

**Comment by avishapiro** [comment]
I believe this has been recently fixed, #33. Try 

```
brew update
brew cask install qlcolorcode
```

**Comment by programming-wolf** [comment]
Hi, thanks for your reply. 
I did that already (I had found the issue #33 ) but it does not change anything. 

Installed QLColorCode version is 2.0.9 (from October 26th, 2017).
Installed highlight version is 3.41_1.
I have created a symlink from `/usr/local/Cellar/highlight/3.41_1/bin/highlight` to `/usr/local/bin/highlight`. Then (and only then) I can see highlighted files like java, javascript, etc. 
However, C# files still do not work at all. 😞

**Comment by anthonygelibert** [comment]
Sorry guy.

Can you please open a terminal and execute this command on a file (copy-paste the result here) :

qlmanage -p -d2 <CS file>

This command will preview the given file with QL with the debug level 2.

Regards,
Anthony.

**Comment by programming-wolf** [comment]
Sorry, I completely forgot about this. Apologies.

Here is the (relevant) output:

```
[DEBUG] Preview test for CoolStuffProvider.cs -- file:///Users/ben/. Content type UTI: dyn.ah62d4rv4ge80g62
[DEBUG] Previewing file:///Users/ben/CoolStuffProvider.cs. Content type UTI: dyn.ah62d4rv4ge80g62. Generator used: <QLGenerator /Users/ben/Library/QuickLook/QLStephen.qlgenerator>
[DEBUG] Loading <QLGenerator /Users/ben/Library/QuickLook/QLStephen.qlgenerator>
[DEBUG] Previewing file:///Users/ben/CoolStuffProvider.cs finished
```

**Comment by anthonygelibert** [comment]
Sorry, for the (very) (very) late answer…

You logs indicate that QLStephen takes the preview, it’s why there is no coloration.

**Comment by anthonygelibert** [comment]
Normally will be fine in the next version
