### ISSUE TITLE
Thumbnail has a weird look

### ISSUE THREAD

**Issue by singularitti** [anthonygelibert/QLColorCode#40]
Glad to see QLColorCode starts to update again!

I am currently satisfied with QLColorCode except one thing: It does not generate correct thumbnails since macOS 10.13 (before 10.13 everything works fine).

For example, the following files are on my macOS:
<img width="875" alt="image" src="https://user-images.githubusercontent.com/25192197/42295996-4711b3d0-7fbe-11e8-9002-6710f30d6877.png">
You can see most of the files are blank except 2: `main.c` and `tv.py`. I guess it should not look like this because in `tv.py` we can clearly see there is a `def` highlighting, which is a part of the whole file. But the correct look before macOS 10.13 should show a minimap of the whole code. And we can see that `main.c` is not correctly rendered either.

I think the problem may come from [the thumbnail size implementation](https://github.com/anthonygelibert/QLColorCode/blob/master/src/GenerateThumbnailForURL.m#L42-44), but I have changed it in several different ways without any improvement. :(

I really hope this issue could be solved since it severely affect the experience when I am using QLColorCode and I am surprised that I do not see any issue talking about it before. Thank you!

**Comment by YiNicer** [comment]
I have the same problem

**Comment by anthonygelibert** [comment]
On my Mac the behavior is pretty strange…  I will investigate this problem…

**Comment by singularitti** [comment]
Some info:
```
System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
```

**Comment by singularitti** [comment]
Any news of fixing?

**Comment by mys721tx** [comment]
On macOS 10.14, the problem still occurs and only the left side of the preview are included in the thumbnail. The thumbnail of `Cargo.toml` on the other hand is provided by `qlstephen`.
<img width="882" alt="screen shot 2018-10-08 at 18 52 33" src="https://user-images.githubusercontent.com/561975/46637688-5252f200-cb2b-11e8-9728-2676ae9d862f.png">

**Comment by singularitti** [comment]
No response, close it.
