### ISSUE TITLE
No preview of file content just an icon...

### ISSUE THREAD

**Issue by Robert-M-Muench** [anthonygelibert/QLColorCode#44]
If I quicklook a source-file only the icon is shown but not the file content. I tried with Finder and PathFinder. 

![screenshot 2018-10-13 19 43 14](https://user-images.githubusercontent.com/1826391/46908248-7003cb00-cf20-11e8-887f-828290de58f4.png)

**Comment by Robert-M-Muench** [comment]
Here is the list of registered file-types:

```
| => qlmanage -m plugins | ag colorcode
  public.c-plus-plus-header -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  com.netscape.javascript-source -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  public.plain-text -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  public.c-plus-plus-source -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  public.source-code -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  com.apple.property-list -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  dyn.ah62d4rv4ge81g25brvuu -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  public.text -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  dyn.ah62d4rv4ge81g6pq -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  dyn.ah62d4rv4ge8007a -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  com.microsoft.f-sharp -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  public.css -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  com.sun.java-class -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  dyn.ah62d4rv4ge80g62 -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  org.tug.tex -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  com.microsoft.c-sharp -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  public.tex -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  dyn.ah62d4rv4ge80s6xbqv0gn -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  public.xml -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  public.php-script -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  org.vim.vim-script -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
  com.apple.applescript.script -> /Users/robby/Library/QuickLook/QLColorCode.qlgenerator (2.1.0 - loaded)
````

**Comment by darkbrow** [comment]
Did you installed highlight?
qlcolorcode needs highlight executable in your path.

**Comment by lintaba** [comment]
same issue
highlight installed:
`
$  ~ : which highlight
/usr/local/bin/highlight
$  ~ : highlight --version

 highlight version 3.47
 Copyright (C) 2002-2018 Andre Simon <andre.simon1 at gmx.de>

 Argparser class
 Copyright (C) 2006-2008 Antonio Diaz Diaz <ant_diaz at teleline.es>

 Artistic Style Classes (3.1)
 Copyright (C) 2006-2018 by Jim Pattee <jimp03 at email.com>
 Copyright (C) 1998-2002 by Tal Davidson

 Diluculum Lua wrapper (1.0)
 Copyright (C) 2005-2013 by Leandro Motta Barros

 xterm 256 color matching functions
 Copyright (C) 2006 Wolfgang Frisch <wf at frexx.de>

 This software is released under the terms of the GNU General Public License.
 For more information about these matters, see the file named COPYING.
`

**Comment by Robert-M-Muench** [comment]
> Did you installed highlight?
> qlcolorcode needs highlight executable in your path.

Great, that seems to fix it. For some source-codes I see line numbers for some not, any option to always show line numbers?

**Comment by schroef** [comment]
@lintaba thanks for the tip! I thought i had it working but wasnt showing anymore. Just installed highight and now does work like a charm
