### ISSUE TITLE
Finder Preview displays icon with small text preview overlaid

### ISSUE THREAD

**Issue by zsiegel92** [anthonygelibert/QLColorCode#48]
When installed, Quicklook works perfectly when you press SPACE on a file.

However, in the "Finder Preview Pane" files display as an icon with a minimal amount of text displayed.

The two screenshots below show the finder preview without QLColorCode (but QLStephen installed for plaintext preview) and with QLColorCode. As you can see, QLColorCode color codes the preview, but displays it overlaid on an icon in a fairly unusable way.

![Screen Shot 2019-04-16 at 2 35 11 PM](https://user-images.githubusercontent.com/26341564/56246367-b0bad900-6056-11e9-9927-cd47b733771a.png)
![Screen Shot 2019-04-16 at 2 35 01 PM](https://user-images.githubusercontent.com/26341564/56246381-b3b5c980-6056-11e9-9455-ea47256f26fc.png)

**Comment by fuzunspm** [comment]
for it's the same when pressing space on a file

**Comment by cylott** [comment]
I have this same issue.

**Comment by Ornataweaver** [comment]
Take the files without any file-extension out of the plugin's supported extensions.

https://github.com/anthonygelibert/QLColorCode/issues/49

**Comment by Ornataweaver** [comment]
Thanks to @darkbrow, We have dark theme version of this plugin.
