### ISSUE TITLE
Request: support for dark mode

### ISSUE THREAD

**Issue by korri123** [anthonygelibert/QLColorCode#49]
Hi, with Mojave there's dark mode and normally quicklook will also be dark. It would be cool if this extension supported dark mode (e.g. dark background)

**Comment by darkbrow** [comment]
To support Mojave's dark mode and to resolve weird icon issue, I'm making dirty workaround code.
to view its code, 
https://github.com/darkbrow/QLColorCode/tree/mojave
or to get quicklook binary, download attached file.
[QLColorCode.qlgenerator.zip](https://github.com/anthonygelibert/QLColorCode/files/3194532/QLColorCode.qlgenerator.zip)

**Comment by singularitti** [comment]
Thank you @darkbrow, I have found this issue ever since macOS 10.13 released. Since then, I abandon `QLColorCode`, and I almost forget what it is like when previewing a code file. Thank you so much!

**Comment by Ornataweaver** [comment]
@darkbrow, thanks a lot for the plugin.

There are some suggestion:
I want my font to be bigger
To have in-Finder preview option. Without this plugin there is in-Finder preview option.

Or take the files without any file-extension out of the plugin's supported extensions.

At the end, merge it to sindresorhus/quick-look-plugins
https://github.com/sindresorhus/quick-look-plugins/issues/109

**Comment by Ornataweaver** [comment]
@darkbrow would you open the issues section on https://github.com/darkbrow/QLColorCode?

**Comment by anthonygelibert** [comment]
Thanks @darkbrow for the dark mode support!
