### ISSUE TITLE
Doesn't work on 10.15

### ISSUE THREAD

**Issue by CarlosAMendoza** [anthonygelibert/QLColorCode#51]
Needs to be signed so macOS can use it.

**Comment by livelaughriley** [comment]
Is this what you're seeing @CarlosAMendoza?

![Screen Shot 2019-09-29 at 8 50 46 AM](https://user-images.githubusercontent.com/34988536/65833459-3beefa80-e296-11e9-9e2c-e6341148fd48.jpg)

However, if I run `qlmanage -p .hyper.js`, I get a full preview:

![Screen Shot 2019-09-29 at 8 55 58 AM](https://user-images.githubusercontent.com/34988536/65833527-f7b02a00-e296-11e9-9d94-7fcf34e55c97.jpg)

**Comment by adityasrini** [comment]
No it does not work. GA Catalina. This is the error message I get:
```
Testing Quick Look preview with files:
	index.js
2019-10-07 20:03:28.975 qlmanage[30011:113479] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6633, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2019-10-07 20:03:33.461 qlmanage[30011:113479] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6e07, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

**Comment by adityasrini** [comment]
I tried the steps from [this issue](https://github.com/whomwah/qlstephen/issues/81) in a related plugin and this time, I get a "this preview cannot be safely displayed in quick look" warning.

**Comment by kallewesterling** [comment]
Same here. When I try to preview a file, here's what I see:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/7298727/66428246-b67cf000-e9e3-11e9-9faa-9a29ca12c0b2.png">

**Comment by rileytwo** [comment]
While notarizing the app would get rid of that notification, I don't think it would solve the overall issue. You can disable that by running `sudo spctl --master-disable` (I'm not recommending doing so, I'm just stating this in case you want to try previewing the file without that notification popping up). 

I'm able to preview the icon, but still no file preview when pressing space. I'm still getting the same file preview as [above](https://github.com/anthonygelibert/QLColorCode/issues/51#issuecomment-536303254)

**Comment by rileytwo** [comment]
After looking around in the logs, I'm able to get this (this is for the `.hyper.js` file above):

`Preview failed due to security risk: web page's main frame was asked to load a url that is not a file URL, and does not conform to html or xml.`

**Comment by sbarex** [comment]
> After looking around in the logs, I'm able to get this (this is for the `.hyper.js` file above):
> 
> `Preview failed due to security risk: web page's main frame was asked to load a url that is not a file URL, and does not conform to html or xml.`

On `GeneratePreviewForUrl.m`, at line 61 you must add the mime type definition to the properies variable. So the patched code is:

```objective-c
CFDictionaryRef properties = (CFDictionaryRef)@{
        (__bridge NSString *)kQLPreviewPropertyTextEncodingNameKey : textEncoding,
        (__bridge NSString *)kQLPreviewPropertyMIMETypeKey : @"text/html",
    };
```

**Comment by sbarex** [comment]
after numerous attempts I have notarized the plugin. After the change I suggested above for adding the mime attribute now works on catalina!

the steps are:
- QLColorCode target, on Build Settings, show all settings and the on signing section set:
  - Code signing identity: "Developer ID Application" 
  - Code signing inject base entitlements: No
  - Code signing style: Manual
  - Developer team: _set your team_
  - Enable hardened runtime: Yes
  - Other code signing flags: --timestamp 
  
Build the plugin then create a zip:
`$ /usr/bin/ditto -c -k --keepParent "*folder containing qlcolorcode.qlgenerator*" QLColorCode.zip`
Then send the zip for notarization whit your appleid user id ad a application password for login:
`xcrun altool --notarize-app --primary-bundle-id "org.n8gray.qlcolorcode" -u "*appleid user name*" -p "*app password appid*" --file QLColorCode.zip`
After the notarization is complete staple the result:
`$ xcrun stapler staple QLColorCode.qlgenerator`

I use an Apple Developer Subscription account. I did not understand if it is possible to notarize with a free account.

I have found more info for notarization on [https://stackoverflow.com/a/56799591/1409904](url)

Anyway Apple has deprecated all quicklook api like `QLPreviewRequestSetDataRepresentation` and suggests to use QLPreviewingController in a Preview Extension (see [http://codeworkshop.net/objc-diff/sdkdiffs/macos/10.15/QuickLook.html](url)). But I don't have found any info for use QLPreviewingController on macos.

**Comment by rileytwo** [comment]
@sbarex the links are taking me to an issue search on this repo

I'm enrolled in the dev program also, but I don't think it's possible to notarize without a paid developer account. There isn't really an official (or clear) statement from apple about it, but everything I've found on the internet points to needing a paid developer account to notarize. Are you not getting any errors in Console.app after adding in those lines?

**Comment by sbarex** [comment]
> @sbarex the links are taking me to an issue search on this repo
> 
> I'm enrolled in the dev program also, but I don't think it's possible to notarize without a paid developer account. There isn't really an official (or clear) statement from apple about it, but everything I've found on the internet points to needing a paid developer account to notarize. Are you not getting any errors in Console.app after adding in those lines?

On Console.app, searching for com.apple.quicklook as suggested from qlmanage with -d arguments (that it is also deprecated...) don't show any errors when open a preview of a source file.

But there are some errors when generating thumbnail on Finder with icon view (in detail view the associated application icons are shows for the file and not the preview):
- No sandbox token for thumbnail request <private>, it will probably fail
- Failed to unarchive thumbnail's generated properties: Error Domain=NSCocoaErrorDomain Code=4865 UserInfo={NSDebugDescription=<private>}

The resulting icon are all black (i use the zenburn theme
With qlmanage -t the icon is generated correctly.

**Comment by rileytwo** [comment]
I was able to get it working with your instructions @sbarex!

**Comment by jonluca** [comment]
Thanks for the help @sbarex - @anthonygelibert is there any chance that a notarized version of the binary will be published/released? 

Additionally, shouldn't disabling notarization `sudo spctl --master-disable` make it work? It's still not working after disabling SIP and notarization.

**Comment by CarlosAMendoza** [comment]
A signed binary would be great for those who don’t have their own developer account. Also thank you for fixing the issue.

**Comment by alexclst** [comment]
Honestly, even though I have a developer account I would rather that the person responsible for past releases make a notarized binary available than building and notarizing this plugin myself, because then the notarization for the plugin is entirely within its actual developer’s account with Apple. I just don’t think that many people should notarize what is the same version of the same plugin, but maybe that is me just figuring it may come back to bite us at some point.

Plus, the issue is with virtually all but one of the QuickLook plugins I had pre-Catalina. We can option-click apps to bypass the security settings stopping us from using them (or at least we could pre-Catalina, haven’t actually run into a need to do that yet on Catalina), but cannot for QuickLook plugins. So another fix would just be an update to Catalina allowing us to option-click plugins to bypass security checks. Unfortunately that doesn’t seem likely to ever happen.

**Comment by rileytwo** [comment]
@alexclst I get what you're saying. I don't think @sbarex was suggesting everyone notarize it themselves (nor was I), but instead was showing how the issue can be resolved. I'm glad that they listed out the steps to "fix" the problem because there's not many other resources to help with a Quick Look problem like this one. 

Since Quick Look plugins are deprecated and will not working in future releases of macOS, it may not be worth @anthonygelibert's time and money to sign up for a developer account just to notarize QLColorCode, if he doesn't already have a developer account.

**Comment by sbarex** [comment]
Unfortunately I don't have a personal developer account to use to share the compiled version of the plugin and I can't use my company account for this.
I really hope Apple doesn't want to delete quicklook because it was a very useful and unique macos feature.
From the little that I understood, however, I think that more developers can notarize the same executable. When executing the program, I suppose macos only checks the presence in Apple's database of a softare that corresponds to a certain hash signed by a certain author and not searching for a specific executable...

**Comment by alexclst** [comment]
Apple isn’t deleting Quick Look, but just requiring that what used to be separate plugins be App Extensions instead. At least, that is my take on seeing Quick Look as a part of the Extensions preferences in System Preferences:

![Screenshot 2019-10-14 at 10 34 07 AM](https://user-images.githubusercontent.com/2946567/66763829-2967ea00-ee6e-11e9-8842-d3b39abd0109.png)

**Comment by adityasrini** [comment]
If the maintainer doesn't have the bandwidth to notarize this, perhaps someone from the community can request to become the maintainer or fork and notarize this themselves?

**Comment by adityasrini** [comment]
I have very limited Objective C knowledge to be able to discern and code review PRs and issue fixes to issues so I'm not so sure about doing this myself.

**Comment by sbarex** [comment]
> Apple isn’t deleting Quick Look, but just requiring that what used to be separate plugins be App Extensions instead. At least, that is my take on seeing Quick Look as a part of the Extensions preferences in System Preferences:
> 
> ![Screenshot 2019-10-14 at 10 34 07 AM](https://user-images.githubusercontent.com/2946567/66763829-2967ea00-ee6e-11e9-8842-d3b39abd0109.png)

oh good! do you have found any source example?

**Comment by rileytwo** [comment]
@sbarex does qlcolorcode still work for you between reboots? Even if I'm able to get it working through building, signing, and notarizing the bundle, it doesn't work the next time I boot my mac up

**Comment by alexclst** [comment]
> oh good! do you have found any source example?

Apple’s sample code for [Building an App Based on the Document Browser View Controller](https://developer.apple.com/documentation/uikit/view_controllers/building_an_app_based_on_the_document_browser_view_controller) discuss previewing custom document formats. This is talking about iOS, but both iOS and macOS now seem to share the same _Quick Look Preview Extension_ target type for building these new App Extension based Quick Look plugins that this sample code includes. I know nothing about the old _.qlgenerator_ plugins at the source level, so would have no way of telling you how different or not this new API is from that which is now deprecated.

**Comment by sbarex** [comment]
> @sbarex does qlcolorcode still work for you between reboots? Even if I'm able to get it working through building, signing, and notarizing the bundle, it doesn't work the next time I boot my mac up

I'm using catalina on vmware fusion for testing before upgrading my mac. For now after the full reboot of the virtual machine the plugin works correctly.

**Comment by sbarex** [comment]
> Apple’s sample code for [Building an App Based on the Document Browser View Controller](https://developer.apple.com/documentation/uikit/view_controllers/building_an_app_based_on_the_document_browser_view_controller) talks about previewing custom document formats. This is talking about iOS, but both iOS and macOS now seem to share the same _Quick Look Preview Extension_ target type for building these new App Extension based Quick Look plugins that this sample code includes. I know nothing about the old _.qlgenerator_ plugins at the source level, so would have no way of telling you how different or not this new API is from that which is now deprecated.

Ok, I saw. I will try to migrate the code on the new system, apparently it does not seem a very complex operation.
Is the new quicklook extension system only valid for catalina? The test plugin I made works on catalina and is seen in the list of extensions while on mojave it does nothing and does not appear in the extensions.

**Comment by Nef10** [comment]
I had a look at migrating the code over, should not be too complex. I experimented with migrating the https://github.com/whomwah/qlstephen plugin and it was fairly easy. But with the plugins running in a sandbox you cannot just call the highlight tool as the path of the homebrew installation is not allowed to be called. I tried adding the binary to my project but it failed because it calls a dsym. Apparently compiling it so that is does not require the dsym is not easy. The easier solution would probably be to do a link to highlight in one of the allowed path from the sandbox, but this needs to be done manually by the user.

**Comment by sbarex** [comment]
I'm converted all objective-c code to swift and I have also implemented a switch for light/dark theme. 

To works the extension must be sandboxed. But a sandboxed code cannot execute shell process, not event call `which highlight`!
After many test I have found a solution using a XPC service dedicated to obtain the formatted code. The XPC may not be sanboxed, so it's can run shell command.
I didn't check if a signed sandbox app require a paid developer account, but for now it seems that the extension does not require notarization.

The advanced of extension is that it's embedded inside an app. So in this app is possible to create an interface to customize the extension (choose the theme for example).

Now I need to make more test before relasing the code.

**Comment by sbarex** [comment]
> I had a look at migrating the code over, should not be too complex. I experimented with migrating the https://github.com/whomwah/qlstephen plugin and it was fairly easy. But with the plugins running in a sandbox you cannot just call the highlight tool as the path of the homebrew installation is not allowed to be called. I tried adding the binary to my project but it failed because it calls a dsym. Apparently compiling it so that is does not require the dsym is not easy. The easier solution would probably be to do a link to highlight in one of the allowed path from the sandbox, but this needs to be done manually by the user.

The solution to embed `higlight` binary inside the extension is not praticable. `colorize.sh` call some other command to preprocess some type of files (decompile applescript and java, convert binary plist, …).
And the embedded `higligligh` should be compile statically, embedding all required libraries (lua, bootstrap, others?) and I don't know how make a fat binary valid for many macos version.

**Comment by Nef10** [comment]
I am by no means an expert - I just spend a couple of hours experimenting. At the end I also found XPC mentioned but did not have any time investigating more, maybe I should have mentioned this. I just wanted to share my insights in case in would help anybody, but seem you have already made more progress than I did :)

Feel free to just put the code up, I can and would like to help testing or whatever else is needed

**Comment by NylonDiamond** [comment]
We're all counting on you guys! You can do it!

**Comment by sbarex** [comment]
Ok, I tried to migrate the qlgenerator to the extension system: [sbarex/QLExt](https://github.com/sbarex/QLExt).
It's a programming exercise, I don't think we can consider it a real application.
I'm not an application developer so the program may have numerous bugs or naivety.

**Comment by NylonDiamond** [comment]
Awesome, thanks for the hard work! Can you give a quick tutorial on how to use this? That would be awesome. I cloned the project but am not so experienced in Xcode and Swift programming. How do I launch the gui/service? Thanks

**Comment by rileytwo** [comment]
@NylonDiamond (this is just my experience)

After cloning the [repo](https://github.com/sbarex/QLExt), open `QLExt.xcodeproj` in Xcode. Build the project (`cmd`+`b`, or pressing the arrow in the top left of the toolbar). After it builds, go to your Xcode derived data folder, which is at `~/Library/Developer/Xcode/DerivedData/`, and find the `QLExt` build.

In my case, it was called `QLExt-aevsjvkhlsnolcgkutvwtnucbwag` (don't mind the extra letters). In that folder, go to `Build/Products/Debug/` and you'll find `QLExt.app`. Copy this to your application folder, open the application, and then press `cmd`+`,` to go to preferences, where you can set up what theme and font you want to use.

**Comment by alexclst** [comment]
I just cloned and built the project. I use Xcode somewhat regularly, so know my way around. However, when I build the app and ensure that the extension is checked in System Preferences I can open files in the app directly and they’ll be previewed, but QuickLook does not seem to recognize the extension. I’ve tried `qlmanage -r`, restarting Finder, restarting quicklookd, logging out and back in, even Archiving the app and running that copy (so it wouldn’t be a Debug build), all to no avail. Since it seems to be working for some, any idea why it may not be working for me?

**Comment by NylonDiamond** [comment]
Awesome, that build process that worked for me as well. I'm able to preview CSS, HTML and PHP at the moment. No javascript, shell scripts or XML. @sbarex did say there would possible be some bugs so it's all good. Just letting people know. Thanks again @sbarex !

**Comment by alexclst** [comment]
Thanks @sbarex for doing this! After first thinking it wasn’t working I see it was just file format issues. I recommend that any of us who have questions or issues regarding this app submit issues over at its [repo](https://github.com/sbarex/QLExt). This is a very great start, and I’m happy to have it back, even if it has a ways still to go to be on par with QLColorCode.

**Comment by sbarex** [comment]
QLColorCode will always remain the number one for me. If his developer want to migrate it to the Catalian extensions I would be happy!
I have addes support for some missing format but there are still bug in my code!

**Comment by NylonDiamond** [comment]
Woo, javascript and .sh works for me now. Those were a couple of the main ones I was needing. Thanks again. Your rock man! Hopefully, there will be support for JSON and othe types in the future.

**Comment by DaveyJake** [comment]
Just wanted to let everyone know that [`QuickLookJSON`](http://www.sagtau.com/quicklookjson.html) is fixed for Catalina.

When looking at the `package contents`, I noticed one major difference: the presence of a folder named **_CodeSignature** which contains a single file named `CodeResources` (no file extension).  It's a `.plist` XML file that documents every file contained within the package and (when necessary) assigns each an internal hash value.  Not sure if that's what needs to be done across all of the QL plugins not currently working but just wanted to share.  Hopefully all will be fixed soon?

**Comment by DaveyJake** [comment]
> Woo, javascript and .sh works for me now. Those were a couple of the main ones I was needing. Thanks again. Your rock man! Hopefully, there will be support for JSON and othe [sic] types in the future.

@NylonDiamond [QuickLookJSON](http://www.sagtau.com/quicklookjson.html) is fixed for Catalina.

**Comment by NylonDiamond** [comment]
Nice!

**Comment by sbarex** [comment]
The _CodeSignature/_CodeSignature contain the signature of the files inside the package. The quicklook generator was notarized by the author. This is why it works.

**Comment by hazarek** [comment]
@sbarex You seem like someone who can fix it. https://github.com/Nyx0uf/qlImageSize/issues/45#issuecomment-540099534

**Comment by lucky13820** [comment]
> Ok, I tried to migrate the qlgenerator to the extension system: [sbarex/SourceCodeSyntaxHighlight](https://github.com/sbarex/SourceCodeSyntaxHighlight).
> It's a programming exercise, I don't think we can consider it a real application.
> I'm not an application developer so the program may have numerous bugs or naivety.

Thanks, your app is working fine.

**Comment by Caf** [comment]
Any chance to have this working from the HomeBrew casks when updated? Thanks for the hard work guys!

**Comment by sbarex** [comment]
Has anyone tried to see if it works on 10.15.1?
I updated my virtual machine and it seems that now the various qlgenerators works but I'm not sure if I did something strange in the settings or if it's a problem solved in the last update.

**Comment by darkbrow** [comment]
It works on my Mac running macOS 10.15.1

**Comment by sbarex** [comment]
Works also for xml and plist format?

**Comment by hazarek** [comment]
> It works on my Mac running macOS 10.15.1

Apple is trying to drive everyone crazy.

**Comment by darkbrow** [comment]
No. It does not work for xml and plist format.

**Comment by vpicouet** [comment]
Hello,
thanks a lot for this work, unfortunately I did not manage to build the app (image).
I am new to Xcode, do you now what's the issue here? 
Thanks!

![Capture d’écran, le 2019-11-13 à 14 49 55](https://user-images.githubusercontent.com/37241971/68769624-ea6fb480-0624-11ea-8549-aeaa706231f9.jpg)

**Comment by sbarex** [comment]
> Hello,
> thanks a lot for this work, unfortunately I did not manage to build the app (image).
> I am new to Xcode, do you now what's the issue here?
> Thanks!
> 
> ![Capture d’écran, le 2019-11-13 à 14 49 55](https://user-images.githubusercontent.com/37241971/68769624-ea6fb480-0624-11ea-8549-aeaa706231f9.jpg)

Have you cloned the project or only download the source code?
You must select the "Syntax Highlight" target on the active scheme popup, Lua libs will be automatically compiled.

The correrct way to download the source is:
```
git clone https://github.com/sbarex/SourceCodeSyntaxHighlight.git
cd SourceCodeSyntaxHighlight
git submodule init  
git submodule update
```
Then open the `SourceCodeSyntaxHighlight.xcodeproj` and select `Syntax hightlight` from active scheme popup.

In my repository there is also the precompiled version of the app so is not required to download and compile manually the source code.

In the future plese notifify any bug inside my repository, thanks.

**Comment by neslob** [comment]
Removing the quarantine attribute from all files is another solution, to get Quicklook working. No need to change any code.

List attributes
`xattr -r ~/Library/QuickLook/QLColorCode.qlgenerator`

Delete attribute _com.apple.quarantine_
`xattr -d -r com.apple.quarantine ~/Library/QuickLook/QLColorCode.qlgenerator`

**Comment by gbstan** [comment]
I have tried using
```
xattr -d -r com.apple.quarantine ~/Library/QuickLook/QLColorCode.qlgenerator
```
on macOS 10.15.2 but it doesn't work (even after relaunching finder or rebooting)

**Comment by neslob** [comment]
> I find QLColorCode very useful and use it daily. It would be very useful if we could get it to work on macOS 10.15, but for the moment this doesn't seem to be the case.
> After installing highlight and QLColorCode from homebrew (brew cask install qlcolorcode highlight)I have tried:
> 
> ```
> xattr -d -r com.apple.quarantine ~/Library/QuickLook/QLColorCode.qlgenerator
> ```
> 
> on macOS 10.15.2 but it doesn't work (even after relaunching finder or rebooting)

maybe there are more quarantine files on your system.

Try the following to delete all of them.
```
# search all
xattr -r ~/Library/QuickLook/QL*
# delete all
xattr -d -r com.apple.quarantine ~/Library/QuickLook/QL
```

**Comment by gbstan** [comment]
Still doesn't work. I have redone everything from scratch
I have reinstalled QLColorCode and highlight from brew and run
```
xattr -d -r com.apple.quarantine ~/Library/QuickLook/QL*
```
After that I have checked that no attribute was remaining by running:
```
xattr -r ~/Library/QuickLook/QL*
```
which returns nothing

**Comment by neslob** [comment]
hmm, no concrete idea. 
try checking where you installation is `mdfind QLColorCode`

**Comment by gbstan** [comment]
@neslob: I see in this thread that (@sbarex)[https://github.com/sbarex] has reconfigured and recompiled the code. Did you install from brew or from another source?

**Comment by gbstan** [comment]
This is what `mdfind QLColorCode` returns:
 ```
/Users/guy-bartstan/Library/QuickLook/QLColorCode.qlgenerator
/usr/local/Caskroom/qlcolorcode
/Users/guy-bartstan/Library/Group Containers/G78RJ6NLJU.group.at.EternalStorms.Yoink/Documents/YoinkPromisedFiles/ESSYoinkSnippets/90E5772D-1DAE-4106-9489-38EBA14D352F.rtf
/usr/local/var/homebrew/locks/198235097cabb60e6828cae82b14a6c6fe7adc49b834548c14c9f644c4c588c3--QLColorCode.qlgenerator.zip.incomplete.lock
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/qlcolorcode.rb
```

**Comment by sbarex** [comment]
> @neslob: I see in this thread that @sbarex has reconfigured and recompiled the code. Did you install from brew or from another source?

My project is not a simple fork of this repository but a different application (which uses the new catalina api for the quicklook extensions) that was inspired by part of this code.

**Comment by neslob** [comment]
> @neslob: I see in this thread that @sbarex has reconfigured and recompiled the code. Did you install from brew or from another source?

Using the original from `brew`. Just went through all steps it works on my side.
1. brew cask uninstall QLColorCode
2. brew cask install QLColorCode
3. create test file `echo -e '#!/bin/bash\n\necho test' > test.sh`
4. test preview should fail `qlmanage -p -g ~/Library/QuickLook/QLColorCode.qlgenerator -c 'public.shell-script' test.sh` 
5. list quarantine files `xattr -r ~/Library/QuickLook/QL* -d com.apple.quarantine` 
6. remoave quarantine `xattr -r -d com.apple.quarantine ~/Library/QuickLook/QL*`
7. preview with color `qlmanage -p -g ~/Library/QuickLook/QLColorCode.qlgenerator -c 'public.shell-script' test.sh`

**Comment by gbstan** [comment]
Ok. This works for me. What doesn't is preview using the space bar on a file to preview it with colours.
If I call the quick preview with the space bar on the file selected in finder, I see the code but no colours.

**Comment by gbstan** [comment]
Is there a step I am missing to allow quicklook preview of code in colours via spacebar on selected files in the finder?

**Comment by gbstan** [comment]
Ok. I got it to work. I had to add `<string>public.shell-script</string>` to the `LSItemContentTypes` section in the file ~//Library/QuickLook/QLColorCode.qlgenerator/Contents/Info.plist

```
<key>LSItemContentTypes</key>
			<array>
				<string>public.shell-script</string>
                               ...
                        </array>
```

**Comment by sbarex** [comment]
For know the UTI of a file do this code in the terminal:
```mdls -name kMDItemContentType filaneme.ext```
where filename.ext is an existing file.

**Comment by gbstan** [comment]
Yes, this works (as indicated for another quicklook plugin [here](https://github.com/whomwah/qlstephen/issues/81#issuecomment-559306570)).

In summary:
1. `brew cask install QLColorCode`
2. `brew install highlight`
3. `xattr -d -r com.apple.quarantine ~/Library/QuickLook/QL*`
4. add `file_UTI` to the LSItemContentTypes section in the file `~/Library/QuickLook/QLColorCode.qlgenerator/Contents/Info.plist` where `file_UTI` is obtained via `mdls -name kMDItemContentType filaneme.ext`

**Comment by SomerledDesign** [comment]
Thank you for this thread.  I performed the above steps and now QLColorCode works with all of my source files (ino,cpp,h,c,cs...)

**Comment by fregante** [comment]
I found a solution that doesn't require editing files.

## Solution

Make sure you follow each step correctly. Please don't leave more unnecessary comments so that new users will see this one.

1. Install the plugin (`brew cask install qlcolorcode `)
2. Select a supported file. macOS will show a warning like this one.
    - **DO NOT CLICK "Move to Trash"**
    - Click "Cancel"
    <img width="532" alt="Cannot be opened because the developer cannot be verified." src="https://user-images.githubusercontent.com/1402241/72137902-41440100-33be-11ea-92f8-6b5e9b2e79d3.png">
3. Open **System Preferences**
4. Visit **Security & Privacy**
5. Ensure you're in the **General** tab. You should see a notice regarding this plugin at the bottom:
    - Click "Allow Anyway"
    <img width="780" alt="qlgenerator was blocked from use because it was not from an identified developer" src="https://user-images.githubusercontent.com/1402241/72138101-a7c91f00-33be-11ea-98f4-1d9734093908.png">
6. Select another supported file **OR** run:
    `qlmanage -p /path/to/any/file.js`
7. You should see a warning similar to the first one, but with a new button
    - Click "Open" 🎉
    <img width="581" alt="Are you sure you want to open it" src="https://user-images.githubusercontent.com/1402241/72138184-d810bd80-33be-11ea-88ca-239998d3f54a.png">
8. Enjoy QuickLooking highlighted files on Catalina
    <img width="604" alt="QLColorCode on Catalina" src="https://user-images.githubusercontent.com/1402241/72138760-15c21600-33c0-11ea-82e1-dc085f440a18.png">

**Comment by adamwinn** [comment]
> Yes, this works (as indicated for another quicklook plugin [here](https://github.com/whomwah/qlstephen/issues/81#issuecomment-559306570)).
> 
> In summary:
> 
>     1. `brew cask install QLColorCode`
> 
>     2. `brew install highlight`
> 
>     3. `xattr -d -r com.apple.quarantine ~/Library/QuickLook/QLColorCode.qlgenerator`
> 
>     4. add `file_UTI` to the LSItemContentTypes section in the file `~/Library/QuickLook/QLColorCode.qlgenerator/Contents/Info.plist` where `file_UTI` is obtained via `mdls -name kMDItemContentType filaneme.ext` (see [here](https://github.com/anthonygelibert/QLColorCode/issues/51#issuecomment-566155289))
> 
> 
> Now QLColorCode should work via spacebar (you might need to relaunch the finder).
> 
> This indicates that the file `~/Library/QuickLook/QLColorCode.qlgenerator/Contents/Info.plist` needs to be updated for Catalina MacOS 10.15(.2) as the file UTI properties seems now to be different from the ones that were recognised on Mojave MacOS 10.14.
> 
> Although it is possible to manually modify the Info.plist file, it would be great if an updated and verified Info.plist for Catalina could be made available.
> 
> **Does anyone know how to create a proper Info.plist for qlcolorcode on Catalina macOS 10.15?**

Why dont you just create a pull request?

**Comment by relikd** [comment]
> The _CodeSignature/_CodeSignature contain the signature of the files inside the package. The quicklook generator was notarized by the author. This is why it works.

Just adding: No you don't need to notorize the plugin for the `_CodeSignature` folder. A normal (unpaid) Apple dev account is sufficient. Not sure if it will help with the call of `highlight` but it might help with other issues.

If you need an example of how to configure the signing, have a look at my [QLOPML](https://github.com/relikd/QLOPML/) plugin (which doesn't use notarization).
I've used the `com.apple.security.app-sandbox` and `com.apple.security.files.user-selected.read-only` entitlements. Using my personal dev account with "Automatically manage singing" and "Development" signing certificate.

**Comment by i0ntempest** [comment]
Thanks @gbstan I add a bunch of extensions into Info.plist and it works great, except xml and plist files are still handled by the default system generator, even it should be handled by QLColorCode:
```
i0ntempest:~ Admin$ qlmanage -m|grep Text
  com.apple.property-list -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
  org.oasis-open.opendocument.text -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
  public.rtf -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
  public.plain-text -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
  com.apple.rtfd -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
  public.xml -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
```
Any ideas?

**Comment by gbstan** [comment]
> Thanks @gbstan I add a bunch of extensions into Info.plist and it works great, except xml and plist files are still handled by the default system generator, even it should be handled by QLColorCode:
> 
> ```
> i0ntempest:~ Admin$ qlmanage -m|grep Text
>   com.apple.property-list -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
>   org.oasis-open.opendocument.text -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
>   public.rtf -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
>   public.plain-text -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
>   com.apple.rtfd -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
>   public.xml -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
> ```
> 
> Any ideas?

I don't really know why this is not dealt with by QLColorCode. Maybe there is an order list for certain files that the OS deals with in priority via its own internal preview? Or, you have certain files that are not captured by the above?

**Comment by i0ntempest** [comment]
> > Thanks @gbstan I add a bunch of extensions into Info.plist and it works great, except xml and plist files are still handled by the default system generator, even it should be handled by QLColorCode:
> > ```
> > i0ntempest:~ Admin$ qlmanage -m|grep Text
> >   com.apple.property-list -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
> >   org.oasis-open.opendocument.text -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
> >   public.rtf -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
> >   public.plain-text -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
> >   com.apple.rtfd -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
> >   public.xml -> /System/Library/QuickLook/Text.qlgenerator (906.2 - loaded)
> > ```
> > 
> > 
> > Any ideas?
> 
> I don't really know why this is not dealt with by QLColorCode. Maybe there is an order list for certain files that the OS deals with in priority via its own internal preview? Or, you have certain files that are not captured by the above?

According to what I found online If two or more generators can open the same UTI the order should be:
(Used first) App bundled generators -> ~/L/Q/ -> /L/Q/ -> /S/L/Q/ (Used last)
I have `public.xml`, `com.apple.property-list` in the Info.plist of QLColorCode. Weird It's still using the system one. So yea, probably OS takes priority on those files... which sucks ¯\_(ツ)_/¯.

**Comment by relikd** [comment]
@i0ntempest Did you try to restart your mac completely? Maybe that will fix the order. Another thing you can try is add the other types for xml as well:
```
kMDItemContentTypeTree = (
    "public.xml",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```
And lastly, did you update Xcode recently? That may have changed the precedence? For me, `xml` and `plist` files are handled by Xcode, not Text. Even though my `qlmanage` output is the same.

**Comment by i0ntempest** [comment]
@relikd You sure your plists are handled by Xcode? For me the generator in Xcode only handles provision profiles. Also I did all you suggested and still nothing. I even tried removing `public.xml` and `com.apple.property-list` from /S/L/Q/Text.qlgenerator. The only way to make it work for me is to temporarily delete /S/L/Q/Text.qlgenerator

**Comment by relikd** [comment]
does it work if you force the generator?
`qlmanage -c public.xml -g ~/Library/QuickLook/QLColorCode.qlgenerator -p ./file.xml`

Though I don't know what to do if it works properly. I am assuming you already `qlmanage -r && qlmanage -r cache`? Last thing you can try is the dyn type for xml: `dyn.ah62d4rv4ge81u5pq`. Other than that I have no ideas left.

**Comment by i0ntempest** [comment]
It does work if I force it, but the dyn type does nothing. Guess I'll have to live with it.

**Comment by i0ntempest** [comment]
I've forked this and added dark mode support and some more. It's more of a programming exercise for me but hopefully it's useful to someone.

**Comment by sbarex** [comment]
> I've forked this and added dark mode support and some more. It's more of a programming exercise for me but hopefully it's useful to someone.

take a look at my repo [sbarex/SourceCodeSyntaxHighlight](https://github.com/sbarex/SourceCodeSyntaxHighlight)

**Comment by kulak** [comment]
> Removing the quarantine attribute from all files is another solution, to get Quicklook working. No need to change any code.
> 
> List attributes
> `xattr -r ~/Library/QuickLook/QLColorCode.qlgenerator`
> 
> Delete attribute _com.apple.quarantine_
> `xattr -d -r com.apple.quarantine ~/Library/QuickLook/QLColorCode.qlgenerator`

Or simply zip files, delete original files and unzip. Works on Windows and Mac.

**Comment by poochwashere** [comment]
Insanely late to the party but [kulak](https://github.com/kulak)'s suggestion worked for me.
