### ISSUE TITLE
Exclude plain text files from supported file types

### ISSUE THREAD

**Issue by Ornataweaver** [anthonygelibert/QLColorCode#52]
The plugin is messing with qlstephen
1. the default dark mode for plain text files https://github.com/anthonygelibert/QLColorCode/issues/49,
2. font size for plain text files,
3. in-Finder Preview displays https://github.com/anthonygelibert/QLColorCode/issues/48

Let qlstephen handle plain text files
https://github.com/whomwah/qlstephen

**Comment by anthonygelibert** [comment]
Done in the latest commit
