### ISSUE TITLE
Language support: Vue

### ISSUE THREAD

**Issue by sdaitzman** [anthonygelibert/QLColorCode#55]
I would love to be able to preview Vue files with QLColorCode.

**Comment by nkalvi** [comment]
@sdaitzman 

Yes, it would be nice to have it included by default.
In the mean time, I added it by following the guide  https://github.com/anthonygelibert/QLColorCode#adding-language-types

```sh
mdls -name kMDItemContentType /path/to/a/file.vue
```
=>
```
kMDItemContentType = "dyn.ah62d4rv4ge81q7pf"
```

Added this type to `Info.plist` under `Document types > Item 0 > Document Content Type UTIs` (using Xcode) - and was able to view `.vue` files right away. 

I'm on `macOS 10.5.3` with `highlight 3.55`.

**Comment by anthonygelibert** [comment]
Done :-)
