### ISSUE TITLE
What's up with the UTIs that QLColorCode declares?

### ISSUE THREAD

**Issue by saagarjha** [anthonygelibert/QLColorCode#56]
I was taking a look at the UTIs that QLColorCode has in its Info.plist and it there seem to be a bunch of dynamic UTIs: https://github.com/anthonygelibert/QLColorCode/blob/ef0edddfb4cc4e03aefb2103dd5f504cd8b0991b/Info.plist#L29 Why aren't we just properly defining them and sticking them in `UTIImportedTypeDeclarations`? Plus, why don't we support files such as `public.c-source` or other common file types?

**Comment by hamiltont** [comment]
Related discussion - https://github.com/whomwah/qlstephen/issues/87

**Comment by ideologysec** [comment]
it looks like this is what macOS does for files that it doesn't know what they are, were created by an application, and are not explicitly plaintext.

ie:
```
$ mdls -name kMDItemContentType /Users/user/Developer/example-repo/example.code-workspace
kMDItemContentType = "dyn.ah62d4rv4ge80g55eqy01s55wrr31a2pdqy"
```

and this is surely something I'd like to see QLColorCode (or qlstephen) support, since it's basically a YAML/JSON file.
