### ISSUE TITLE
3.0.2 is broken

### ISSUE THREAD

**Issue by JimAmuro** [anthonygelibert/QLColorCode#62]
Hi, I am using macos 10.15.6, and I cannot use the latest version. The system says the plugin is broken...

**Comment by anthonygelibert** [comment]
Hhmmm… I use it right now… So… I don't know where is the problem… I will try to edit the binary associated to the release…

**Comment by JimAmuro** [comment]
Sorry, my bad... Don't know why the plugin got quarantined again after the upgrade... Solved by removing quarantine attributes. Thanks for the timely response!

**Comment by insipidlight** [comment]
I'm still having this same issue. It installs correctly, but the system never asks for quarantine.

`“QLColorCode.qlgenerator” is damaged and can’t be opened. You should move it to the Trash.`

**Comment by JimAmuro** [comment]
@insipidlight This just means it got quarantined by Catalina... 
You may run `xattr -d -r com.apple.quarantine ~/Library/QuickLook` at terminal and try quicklook again.
