### ISSUE TITLE
Not working for .sql files

### ISSUE THREAD

**Issue by CrisVM** [anthonygelibert/QLColorCode#65]
Hi.

Since last update _(done via Homebrew)_, **.sql** files don't work properly with **QLColorCode** anymore.

Maybe it's because of **Highlight** being also updated, but I'm not able to tell where the problem really is.

Any help will be greatly appreciated.

Thanks.
Cristiano

**Comment by CrisVM** [comment]
I just realized **.asp** and **.txt** files don't work as well. There may be more file types not working... 😕

**.txt** file _(not rendering through **QLColorCode**)_:
![ZION³ 2020-09-18 at 16 46 26](https://user-images.githubusercontent.com/3301474/93638994-abda2180-f9ce-11ea-9e55-a9e2749dafad.png)

**.sh** file _(rendering through **QLColorCode**)_:
![ZION³ 2020-09-18 at 16 46 57](https://user-images.githubusercontent.com/3301474/93639146-ecd23600-f9ce-11ea-9f22-584d86f552f1.png)

**Comment by anthonygelibert** [comment]
> Hi.
> 
> Since last update _(done via Homebrew)_, **.sql** files don't work properly with **QLColorCode** anymore.
> 
> Maybe it's because of **Highlight** being also updated, but I'm not able to tell where the problem really is.
> 
> Any help will be greatly appreciated.
> 
> Thanks.
> Cristiano

Can you provide me an SQL file that is not working, please? I can't reproduce locally the problem.

**Comment by anthonygelibert** [comment]
> I just realized **.asp** and **.txt** files don't work as well. There may be more file types not working... 😕
> 
> **.txt** file _(not rendering through **QLColorCode**)_:
> ![ZION³ 2020-09-18 at 16 46 26](https://user-images.githubusercontent.com/3301474/93638994-abda2180-f9ce-11ea-9e55-a9e2749dafad.png)
> 
> **.sh** file _(working as expected)_:
> ![ZION³ 2020-09-18 at 16 46 57](https://user-images.githubusercontent.com/3301474/93639146-ecd23600-f9ce-11ea-9f22-584d86f552f1.png)

For TXT, it's not a bug but a feature ;-) (see #48, I removed the TXT file support in favor of QLStephen). For ASP, can you provide me a file, please ?

**Comment by CrisVM** [comment]
Hi @anthonygelibert 

Sorry for the late reply...

Inside this zip file, there are 2 files: **sample.asp**, and **sample.sql**
[samples.zip](https://github.com/anthonygelibert/QLColorCode/files/5265497/samples.zip)

Please, take a look at the following screenshot:
![ZION³ 2020-09-23 at 01 16 15](https://user-images.githubusercontent.com/3301474/93966193-715be600-fd3a-11ea-83ad-4a0cfb53e1f3.png)

As you can see, there's a reason for **.asp** files not use **QLColorCode**... :-) I'm just not sure how to "fix" it...

Does it have anything to do with editing the **Info.plist** file? _(as described in the README.md)_

If so, is this the same procedure I have to do in order to make **.txt** files use **QLColorCode** as well?

And then there's the **.sql** files that still make me wonder what's going on...

If you need further details, please let me know.

Thank you so much for your time.
Cristiano.

**Comment by CrisVM** [comment]
Hi again.

I kind of _"fixed"_ everything but **.sql** files to my liking...

I just edited Info.plist adding these lines inside the **LSItemContentTypes** array:

```xml
	<string>public.plain-text</string>
	<string>public.data</string>
	<string>public.content</string>
```
And then I uninstalled **QLStephen**, 'cause these edits made **QLColorCode** render everything that **QLStephen** would, so I don't need it anymore... :-)

The only files that are still _"broken"_: **.sql**

Any news on this?

Thanks again.
Cristiano.

**Comment by CrisVM** [comment]
Update:

I don't know why, but now **.sql** files work as expected. 8-)
![ZION³ 2020-09-23 at 13 31 03](https://user-images.githubusercontent.com/3301474/94041970-53759c00-fda1-11ea-9077-6333fd794b6a.png)

Maybe there was some cache going on... I don't know.

Anyway, thank you so much for taking the time to look at this issue for me. I really appreciate it!

Cheers.
Cristiano.
