### ISSUE TITLE
Error when adding .tf and .tfvars files to types (macOS Catalina 10.15.7 (19H2))

### ISSUE THREAD

**Issue by duch11** [anthonygelibert/QLColorCode#70]
Hello I've installed this plugin from homebrew.
I would love to be able to see terraform files as well. 
I've tried adding it to the list, but finder bugs out, and only shows a tiny text version of the source code, that is fine, better than nothing, but I would like to at least be able to read it. 😄 
 
(syntax highlighting is not really needed if that makes it easier)

Please let me know, what you'll need to add this to the script. :) 

Thank you!

**Comment by duch11** [comment]
*.tfvars
kMDItemContentType = "dyn.ah62d4rv4ge81k3x0qf3hg"

*.tf
kMDItemContentType = "dyn.ah62d4rv4ge81k3u"

**Comment by anthonygelibert** [comment]
I add it right now!
