### ISSUE TITLE
Possibility to set Font family with spaces in name?

### ISSUE THREAD

**Issue by mgrn0** [anthonygelibert/QLColorCode#71]
How / or is it even possible to set a font family name that includes spaces, e.g. 'Jet Brains Mono'? I tried with quotation marks, camel casing, ... none of these worked.

**Comment by anthonygelibert** [comment]
Are you sure… I use JetBrains Mono font… So, it should works?

`defaults write org.n8gray.QLColorCode font "JetBrains Mono"`

**Comment by mgrn0** [comment]
Thanks so much - I don't know what is different but it works now for me, too.
