### ISSUE TITLE
Travis build cannot target MACOSX_DEPLOYMENT_TARGET=11.1

### ISSUE THREAD

**Issue by jeffbyrnes** [anthonygelibert/QLColorCode#75]
🎉 Hooray for the v4.0.0 being released with Big Sur support!

However, it looks like Travis is lagging a bit on build support for macOS v11.1.0: https://travis-ci.org/github/anthonygelibert/QLColorCode/builds/749884374

This has prevented the build from shipping v4.0.0 to Homebrew.

**Comment by anthonygelibert** [comment]
Sorry! I fix it and release a 4.0.1! My bad 😔…

**Comment by anthonygelibert** [comment]
Fixed 😊

**Comment by jeffbyrnes** [comment]
All good, @anthonygelibert! Thanks for the quick fix.
