### ISSUE TITLE
Readme needs updating

### ISSUE THREAD

**Issue by ralphrmartin** [anthonygelibert/QLColorCode#76]
I believe this is no longer true, as highlight is incvluded, so needs removing:

Warning: my fork uses an external Highlight. It will attempt to find highlight on your PATH (so it should work out of the box for Homebrew and MacPorts), but if it can't find it, it'll use /opt/local/bin/highlight (MacPorts default). This can be changed:

defaults write org.n8gray.QLColorCode pathHL /path/to/your/highlight

**Comment by anthonygelibert** [comment]
Look at the latest commit please. Reopen the issue if required 😊.
