### ISSUE TITLE
version number broken in 4.0 and 4.0.1

### ISSUE THREAD

**Issue by core-code** [anthonygelibert/QLColorCode#77]
both new versions still claim to be version 3.1.1

both CFBundleShortVersionString and CFBundleVersion were not properly updated for the new releases

<img width="670" alt="Screenshot 2020-12-16 at 13 24 25" src="https://user-images.githubusercontent.com/1261954/102348424-2bfa2e00-3fa2-11eb-8b82-bb03e8df67a9.png">

**Comment by anthonygelibert** [comment]
Normally, the new 4.0.2 is ok.

**Comment by core-code** [comment]
thanks!

**Comment by anthonygelibert** [comment]
Fixed!

**Comment by core-code** [comment]
thanks i can confirm it is resolved
