### ISSUE TITLE
Decrease the minimal macOS version supported by QLColorCode

### ISSUE THREAD

**Issue by justdayan** [anthonygelibert/QLColorCode#79]
qlcolorcode 3.1.1 -> 4.0.2
```
==> Upgrading qlcolorcode
==> Purging files for version 4.0.2 of Cask qlcolorcode
Error: qlcolorcode: macOS Catalina or newer is required for this software.
```

**Comment by anthonygelibert** [comment]
It's a (pretty) good question… I only have Big Sur to test… If you are able to check on older system and update the values to allow them… Fill a pull request 😉.

**Comment by aaronslwalker** [comment]
I got 4.1.0 installed on Mojave by editing the homebrew file and it seems to be working well:

`brew edit qlcolorcode`

Modify the file to contain:

`depends_on macos: ">= :mojave"`

**Comment by anthonygelibert** [comment]
It's an homebrew modification… Can you report to them?

**Comment by aaronslwalker** [comment]
PR submitted to Homebrew to reduce required macOS version to Mojave:

https://github.com/Homebrew/homebrew-cask/pull/97096
