### ISSUE TITLE
Default Window Size

### ISSUE THREAD

**Issue by faberchri** [anthonygelibert/QLColorCode#8]
Could you add a possibility to specify the window size of the quicklook window? I couldn't figure out how to customize that. Would be great!

**Comment by anthonygelibert** [comment]
Hi,

I’ve an idea to implement this feature. I do it ASAP (but I’m pretty busy currently).

Regards,
Anthony.

**Comment by saagarjha** [comment]
@faberchri Would you mind opening up `Info.plist` and trying to set the width and height there? You can find `Info.plist` by going to `~/Library/Quicklook` (open Finder, press Command-Shift-G, then pasting the path and pressing enter), finding `QLColorCode.qlgenerator`, right clicking and selecting "Show Original", then right clicking on the new `QLColorCode.qlgenerator` shown and selecting "Show Package Contents". Double click on the `Contents` folder, then open `Info.plist` in something like TextEdit.
In the file, you will find something that looks like this near the top:
```
	<key>QLPreviewHeight</key>
	<integer>640</integer>
	<key>QLPreviewWidth</key>
	<real>800</real>
```
Could you try changing the `640` and the `800` and seeing if that changes the default for you? If it does we could probably change the plist programmatically later.

**Comment by faberchri** [comment]
Changing the` Info.plist` did not change the window size.

**Comment by saagarjha** [comment]
I'm guessing that `integer` key should be a `real`. Could you try changing it and trying again?

**Comment by tsouchlarakis** [comment]
Confirming that this solution does work, modifying `Info.plist` and changing `integer` to `real`.

**Comment by anthonygelibert** [comment]
Change done in the latest commits.
